import { describe, expect, it } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import type { ClozeFields, QAFields } from "../store";
import { importApkg } from "./apkg";

// Generated by `npm run fixture:anki` (needs the anki python package). Skipped
// when absent so a fresh clone can still run the suite.
const FIXTURE = resolve(process.cwd(), "tmp/anki-export.apkg");
const hasFixture = existsSync(FIXTURE);

describe.skipIf(!hasFixture)("importing a deck exported by Anki itself", () => {
    const load = () => importApkg(new Blob([readFileSync(FIXTURE)]));

    it("reads the deck name and both stock notetypes", async () => {
        const result = await load();
        expect(result.deckName).toBe("Biology 101");
        expect(result.cards).toHaveLength(2);
        expect(result.skipped).toBe(0);
        expect(result.cards.map((card) => card.kind).sort()).toEqual(["cloze", "qa"]);
    });

    it("maps Basic to a question and answer card, with its image", async () => {
        const result = await load();
        const qa = result.cards.find((card) => card.kind === "qa")!;
        const fields = qa.fields as QAFields;

        expect(fields.front).toContain("What does this show?");
        expect(fields.back).toContain("<b>cell</b>");
        expect(result.media.map((record) => record.filename)).toEqual(["cell.png"]);
        expect(fields.front).toContain(`data-media-id="${result.media[0].id}"`);
    });

    it("keeps the hint and reports the multi-number blank", async () => {
        const result = await load();
        const cloze = result.cards.find((card) => card.kind === "cloze")!;
        const fields = cloze.fields as ClozeFields;

        expect(fields.text).toContain('data-cloze="1" data-hint="organelle"');
        expect(fields.text).toContain("mitochondrion");
        expect(fields.text).toContain('data-cloze="2"');
        expect(fields.extra).toContain("Cell biology");
        expect(result.warnings.join(" ")).toContain("several numbers");
        expect(result.warnings.join(" ")).toContain("new cards rather than updating");
        expect(cloze.id).toMatch(
            /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
        );
    });
});
